### PR TITLE
implemented support for "require()" calls removal

### PR DESCRIPTION
**Pull request by slavafomin**
**Multiple changes:**
- implemented support for `require()` calls removal
- refactored tests system

_Signed-off-by: Slava Fomin II <slava@fomin.io>_

### CODE REVIEW

**Comment by slavafomin** [comment]
Hey @jaywcjlove! I've added ability to not only remove ESM imports, but also the CommonJS ones (`require()` calls). This will allow to use this plugin for a wider range of cases. I've also refactored the tests system to make it much more maintainable and scalable.

I will greatly appreciate if you would be able to merge it and release the changes in a timely manner, because I desperately need this functionality in our project. Thanks!

**Comment by slavafomin** [comment]
Published temporarily under `@moebius/babel-plugin-transform-remove-imports`.

**Comment by jaywcjlove** [comment]
@slavafomin thx! Upgrade `+ babel-plugin-transform-remove-imports@1.5.0`

**Comment by slavafomin** [comment]
Good news, thanks )

**Pull request merged**
